### PR TITLE
Packit: remove el8 and add centos stream 10

### PR DESCRIPTION
**Pull request by lsm5**
EL8 will go EOL soon and centos stream 10 is now available in copr.

### CODE REVIEW

**Comment by lsm5** [comment]
@rhatdan the latest tag pushed was `2.231.0` but we need `v2.231.0`. Could you please push this tag as well? Also need the github release created to get packit builds going.

**Comment by lsm5** [comment]
@edsantiago PTAL at centos-stream-10 failures

**Comment by edsantiago** [comment]
Looking at [one of those](https://artifacts.dev.testing-farm.io/20475b60-a071-41c4-a410-d1d95429ced2/) I see red:
```
Errors during downloading metadata for repository 'baseos':
  - Curl error (28): Timeout was reached for https://odcs.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Failed to connect to odcs.stream.centos.org port 443 after 30001 ms: Timeout was reached]
  - Curl error (28): Timeout was reached for https://odcs.stream.centos.org/stream-10/production/latest-CentOS-Stream/compose/BaseOS/x86_64/os/repodata/repomd.xml [Failed to connect to odcs.stream.centos.org port 443 after 30000 ms: Timeout was reached]
Error: Failed to download metadata for repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
...which doesn't look like anything related to anything on our end. Is there a re-run button for these?

**Comment by lsm5** [comment]
>  Is there a re-run button for these?

@edsantiago Yes, click Details to see the re-run button against the test. Anyway, I reran it and that flake has gone away, now there are some real failures.

**Comment by edsantiago** [comment]
Flakes galore:
```
  Error: initializing source docker://registry.fedoraproject.org/fedora-toolbox:36: \
     pinging container registry registry.fedoraproject.org: \
     Get "https://registry.fedoraproject.org/v2/": \
     dial tcp: lookup registry.fedoraproject.org: Temporary failure in name resolution
```

**Comment by lsm5** [comment]
> Flakes galore:
> 
> ```
>   Error: initializing source docker://registry.fedoraproject.org/fedora-toolbox:36: \
>      pinging container registry registry.fedoraproject.org: \
>      Get "https://registry.fedoraproject.org/v2/": \
>      dial tcp: lookup registry.fedoraproject.org: Temporary failure in name resolution
> ```

ugh, rerunning

**Comment by edsantiago** [comment]
Oooh, the [system test](https://artifacts.dev.testing-farm.io/68709770-20f1-45be-a794-e7e36c91ce0a/) looks unpleasant:
```
# [14:48:00.647461654] Error: netavark: unable to append rule '! -d 224.0.0.0/4 -j MASQUERADE' to table 'nat': code: 4, msg: Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
# iptables v1.8.10 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain NETAVARK-1D8721804F16F
```
@Luap99 does that look familiar?

**Comment by lsm5** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM
thanks @lsm5

**Pull request merged**
