### PR TITLE
Makefile: install.udica-templates target

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

### CODE REVIEW

**Comment by lsm5** [comment]
there's a few more things coming in ...

**Comment by lsm5** [comment]
alright so the packit build failures are consistent with https://github.com/containers/container-selinux/issues/203 . But rawhide seems to be well.

**Comment by vmojzis** [comment]
LGTM (corresponds to fedora spec file)

**Comment by lsm5** [comment]
made some more changes to the Makefile, PTAL.

**Comment by lsm5** [comment]
making another change to packit ...

**Comment by lsm5** [comment]
@rhatdan @vmojzis Ready for a second review. I added the DATADIR variable to Makefile and also reconfigured .packit.yaml to use our custom copr project and run builds for Fedora 37+ and CentOS Stream 8+ .

**Comment by rhatdan** [comment]
LGTM

**Comment by lsm5** [comment]
weird. If this was merged into main 2 weeks ago, why are these changes not visible in the main branch right now?

**Pull request merged**
