### PR TITLE
Rename all /var/run file context entries to /run

### PR DESCRIPTION
**Pull request by zpytela**
With the 1f76e522a ("Rename all /var/run file context entries to /run") selinux-policy commit, all /var/run file context entries moved to /run and the equivalency was inverted. Subsequently, changes in container.fc need to be done, too, in a similar manner. Together with that, the "/run/lock = /var/lock" equivalency was also inverted and entries moved.

### CODE REVIEW

**Comment by zpytela** [comment]
Please note this change is F40+ only and will subsequently apply to RHEL 10, not earlier releases. This change should require >= selinux-policy-40.12-1.fc40.

**Comment by rhatdan** [comment]
This means we need the spec file to modify the fcontext file with something like

sed 's|^/run|/var/run|g' -i container-selinux.fc

Can you modify the spec file to do this on < f40 and < RHEL10

**Comment by zpytela** [comment]
I've updated the PR in a way that mimics other similar conditions, not actually tested in different environments though.

**Comment by rhatdan** [comment]
LGTM
@lsm5 PTAL

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
i think el8 tests might fail until we have https://github.com/containers/container-selinux/pull/299 merged.

**Pull request merged**
