### PR TITLE
Add /usr/local/bin/docker.*

### LINKED ISSUE #99: Support `/usr/local` for all binaries?
https://github.com/containers/container-selinux/blob/988431700370bf7f554ab6507c836a9aa19e47ff/container.fc

Currently, only `podman`, `runc`, `crun`, and `crio` are supported for `/usr/local` installation.

I'd expect `/usr/local` installation to be supported for all binaries.

Ref: https://github.com/containerd/containerd/pull/4346

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #99

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
cc @thaJeztah (https://github.com/docker/containerd-packaging/pull/194#issuecomment-673401411)

**Comment by thaJeztah** [comment]
Thanks! Can you also update the man page? For containerd, `/usr/local/containerd..` was missing; https://github.com/containers/container-selinux/blob/ae0720d6ac32866b023babeff75e766870951f8f/container_selinux.8#L312

And the paths added in this PR should probably also be listed in their corresponding lines, e.g. https://github.com/containers/container-selinux/blob/ae0720d6ac32866b023babeff75e766870951f8f/container_selinux.8#L312

**Comment by thaJeztah** [comment]
Off-topic, but curious; I see the profile has entries for `/var/run/xxxx`, but not for `/run/xxx` https://github.com/containers/container-selinux/blob/ae0720d6ac32866b023babeff75e766870951f8f/container.fc#L87-L94

`/var/run` is usually symlinked to `/run`, but wondering if both should have an entry (and/or if `/run`, being the "canonical" location, should be the one listed in the profile)

**Comment by rhatdan** [comment]
In the upstream policy, they map all /run/* to /var/run/* so we only need to do this for /run

```
$ cat /etc/selinux/targeted/contexts/files/file_contexts.subs_dist 
/run /var/run
/run/lock /var/lock
/run/systemd/system /usr/lib/systemd/system
/run/systemd/generator /usr/lib/systemd/system
/run/systemd/generator.late /usr/lib/systemd/system
/lib /usr/lib
/lib64 /usr/lib
/usr/lib64 /usr/lib
/usr/local/lib64 /usr/lib
/usr/local/lib32 /usr/lib
/etc/systemd/system /usr/lib/systemd/system
/var/lib/xguest/home /home
/var/named/chroot/usr/lib64 /usr/lib
/var/named/chroot/lib64 /usr/lib
/var/named/chroot/var  /var
/home-inst            /home
/home/home-inst            /home
/var/roothome        /root
/sbin                /usr/sbin
/sysroot/tmp         /tmp
/var/usrlocal        /usr/local
```

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Sadly they don't do /usr/local/bin -> /usr/bin  but they probably should.

**Comment by rhatdan** [comment]
@AkihiroSuda Do you need a release or can you wait until next time their is a change in the te file?

**Comment by AkihiroSuda** [comment]
I can wait, thanks

**Pull request merged**
