### PR TITLE
Add udica policy templates

### PR DESCRIPTION
**Pull request by vmojzis**
Move udica policy templates here so that administrators can deploy
udica-generated policies on OpenShift nodes without installing udica
everywhere.

Signed-off-by: Vit Mojzis <vmojzis@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Will this conflict with the udica package install?

@wrabcak WDYT?

**Comment by vmojzis** [comment]
> Will this conflict with the udica package install?
As it is now, yes. I'll need to make a new release without the templates.
Udica will need `Requires: container-selinux >= container-selinux-2.168.0-1` and `Conflicts: container-selinux < container-selinux-2.168.0-1`.

Or, we could ship the templates in another directory and update udica to use the new template store. Udica would still need `Requires: container-selinux >= container-selinux-2.168.0-1`, but there would be no conflict.

**Comment by vmojzis** [comment]
Actually, the "Conflicts" statement should go to container-selinux (to also avoid clashes with older versions of udica), you're right.

**Comment by wrabcak** [comment]
@rhatdan , we need to solve the conflicts and deliver this PR. There is a valid use-case when you want to use udica generated policy (using these templates), but there is no need to install udica package. It could be handled by container-selinux package.

**Comment by rhatdan** [comment]
I am fine with merging it upstream, but we are going to need to coordinate a release of udica and container-selinux to make this go smoothly.  We can add a conflicts with udica < SOMEVERSION to the rpm spec file.

**Pull request merged**
