### PR TITLE
container.fc: label {var/srv,srv}/containers as container_file_t

### PR DESCRIPTION
**Pull request by mike-nguyen**
Partially addresses:
https://github.com/coreos/fedora-coreos-tracker/issues/42

### CODE REVIEW

**Comment by rhatdan** [comment]
Why do you want to make these directories writable by all containers?

**Comment by rhatdan** [comment]
@dustymabe and I had a discussion over in Fedora land. 
LGTM

**Comment by rhatdan** [comment]
Building container-selinux-2.104-1.git7baad79.fc*

**Comment by dustymabe** [comment]
> @dustymabe and I had a discussion over in Fedora land.

Thanks Dan. For those following along at home that referenced discussion started [here](https://src.fedoraproject.org/rpms/skopeo/pull-request/2#comment-26025)

**Pull request merged**
