### PR TITLE
New alias for container_share_t type

### PR DESCRIPTION
**Pull request by wrabcak**
container_share_t is read-only type for container_t process. It's
confusing for users so this commit adds new alias "container_ro_t" for
contianer_share_t which make more sense.

### CODE REVIEW

**Comment by rhatdan** [comment]
Should the default name be container_ro_t?

**Comment by rhatdan** [comment]
Or better yet container_ro_file_t or container_file_ro_t

**Comment by wrabcak** [comment]
@rhatdan  that's the best solution, yes, but do you want to do some big change in container policy?

**Comment by wrabcak** [comment]
@rhatdan I made container_ro_file_t default and container_share_t alias.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
