### PR TITLE
tmt: run podman system tests correctly

### PR DESCRIPTION
**Pull request by lsm5**
@edsantiago said specifying the podman binary path in system tests is not correct usage.

### CODE REVIEW

**Comment by edsantiago** [comment]
LGTM!

**Comment by edsantiago** [comment]
It's the crun bug
```
# [09:29:48.349541118] Error: OCI runtime error: crun: unknown version specified
```

**Comment by lsm5** [comment]
wonder why none of the packit tasks are running

**Comment by lsm5** [comment]
@edsantiago @rhatdan good to go. PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by edsantiago** [comment]
Belated LGTM2

**Pull request merged**
